# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-15 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=250)),
                ('height', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=250)),
                ('genre', models.CharField(max_length=250)),
                ('number_of_awards', models.CharField(max_length=250)),
                ('time_of_movie', models.CharField(max_length=250)),
                ('director', models.CharField(max_length=250)),
                ('scenarist', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='movie_star',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movies'),
        ),
    ]
