# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-15 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_star',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movies.Movies'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie_star',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
